cc_library(
	name = "695MaxAreaofIsland",
	hdrs = ["695.MaxAreaofIsland.h"],
	srcs = ["695.MaxAreaofIsland.cpp"]
)

cc_binary(
	name  = "695MaxAreaofIslandTest",
	srcs  = ["695.MaxAreaofIslandTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["695MaxAreaofIsland",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "547NumberofProvinces",
	hdrs = ["547.NumberofProvinces.h"],
	srcs = ["547.NumberofProvinces.cpp"]
)

cc_binary(
	name  = "547NumberofProvincesTest",
	srcs  = ["547.NumberofProvincesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["547NumberofProvinces",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "417PacificAtlanticWaterFlow",
	hdrs = ["417.PacificAtlanticWaterFlow.h"],
	srcs = ["417.PacificAtlanticWaterFlow.cpp"]
)

cc_binary(
	name  = "417PacificAtlanticWaterFlowTest",
	srcs  = ["417.PacificAtlanticWaterFlowTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["417PacificAtlanticWaterFlow",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "934ShortestBridge",
	hdrs = ["934.ShortestBridge.h"],
	srcs = ["934.ShortestBridge.cpp"]
)

cc_binary(
	name  = "934ShortestBridgeTest",
	srcs  = ["934.ShortestBridgeTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["934ShortestBridge",
			 "@googletest//:gtest_main"],
)
