cc_library(
	name = "695MaxAreaofIsland",
	hdrs = ["695.MaxAreaofIsland.h"],
	srcs = ["695.MaxAreaofIsland.cpp"]
)

cc_binary(
	name  = "695MaxAreaofIslandTest",
	srcs  = ["695.MaxAreaofIslandTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["695MaxAreaofIsland",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "17LetterCombinationsofaPhoneNumber",
	hdrs = ["17.LetterCombinationsofaPhoneNumber.h"],
	srcs = ["17.LetterCombinationsofaPhoneNumber.cpp"]
)

cc_binary(
	name  = "17LetterCombinationsofaPhoneNumberTest",
	srcs  = ["17.LetterCombinationsofaPhoneNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["17LetterCombinationsofaPhoneNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "547NumberofProvinces",
	hdrs = ["547.NumberofProvinces.h"],
	srcs = ["547.NumberofProvinces.cpp"]
)

cc_binary(
	name  = "547NumberofProvincesTest",
	srcs  = ["547.NumberofProvincesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["547NumberofProvinces",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "417PacificAtlanticWaterFlow",
	hdrs = ["417.PacificAtlanticWaterFlow.h"],
	srcs = ["417.PacificAtlanticWaterFlow.cpp"]
)

cc_binary(
	name  = "417PacificAtlanticWaterFlowTest",
	srcs  = ["417.PacificAtlanticWaterFlowTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["417PacificAtlanticWaterFlow",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "934ShortestBridge",
	hdrs = ["934.ShortestBridge.h"],
	srcs = ["934.ShortestBridge.cpp"]
)

cc_binary(
	name  = "934ShortestBridgeTest",
	srcs  = ["934.ShortestBridgeTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["934ShortestBridge",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "130SurroundedRegions",
	hdrs = ["130.SurroundedRegions.h"],
	srcs = ["130.SurroundedRegions.cpp"]
)

cc_binary(
	name  = "130SurroundedRegionsTest",
	srcs  = ["130.SurroundedRegionsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["130SurroundedRegions",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "37SudokuSolver",
	hdrs = ["37.SudokuSolver.h"],
	srcs = ["37.SudokuSolver.cpp"]
)

cc_binary(
	name  = "37SudokuSolverTest",
	srcs  = ["37.SudokuSolverTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["37SudokuSolver",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "39CombinationSum",
	hdrs = ["39.CombinationSum.h"],
	srcs = ["39.CombinationSum.cpp"]
)

cc_binary(
	name  = "39CombinationSumTest",
	srcs  = ["39.CombinationSumTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["39CombinationSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "60PermutationSequence",
	hdrs = ["60.PermutationSequence.h"],
	srcs = ["60.PermutationSequence.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "60PermutationSequenceTest",
	srcs  = ["60.PermutationSequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["60PermutationSequence",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "93RestoreIPAddresses",
	hdrs = ["93.RestoreIPAddresses.h"],
	srcs = ["93.RestoreIPAddresses.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "93RestoreIPAddressesTest",
	srcs  = ["93.RestoreIPAddressesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["93RestoreIPAddresses",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "174DungeonGame",
	hdrs = ["174.DungeonGame.h"],
	srcs = ["174.DungeonGame.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "174DungeonGameTest",
	srcs  = ["174.DungeonGameTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["174DungeonGame",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "200NumberofIslands",
	hdrs = ["200.NumberofIslands.h"],
	srcs = ["200.NumberofIslands.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "200NumberofIslandsTest",
	srcs  = ["200.NumberofIslandsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["200NumberofIslands",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "399EvaluateDivision",
	hdrs = ["399.EvaluateDivision.h"],
	srcs = ["399.EvaluateDivision.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "399EvaluateDivisionTest",
	srcs  = ["399.EvaluateDivisionTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["399EvaluateDivision",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "909SnakesandLadders",
	hdrs = ["909.SnakesandLadders.h"],
	srcs = ["909.SnakesandLadders.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "909SnakesandLaddersTest",
	srcs  = ["909.SnakesandLaddersTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["909SnakesandLadders",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "433MinimumGeneticMutation",
	hdrs = ["433.MinimumGeneticMutation.h"],
	srcs = ["433.MinimumGeneticMutation.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "433MinimumGeneticMutationTest",
	srcs  = ["433.MinimumGeneticMutationTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["433MinimumGeneticMutation",
			 "@googletest//:gtest_main"],
)