cc_library(
	name = "69Sqrtx",
	hdrs = ["69.Sqrt(x).h"],
	srcs = ["69.Sqrt(x).cpp"]
)

cc_binary(
	name  = "69SqrtxTest",
	srcs  = ["69.Sqrt(x)Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["69Sqrtx",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "34FindFirstandLastPositionofElementinSortedArray",
	hdrs = ["34.FindFirstandLastPositionofElementinSortedArray.h"],
	srcs = ["34.FindFirstandLastPositionofElementinSortedArray.cpp"]
)

cc_binary(
	name  = "34FindFirstandLastPositionofElementinSortedArrayTest",
	srcs  = ["34.FindFirstandLastPositionofElementinSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["34FindFirstandLastPositionofElementinSortedArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "81SearchinRotatedSortedArrayII",
	hdrs = ["81.SearchinRotatedSortedArrayII.h"],
	srcs = ["81.SearchinRotatedSortedArrayII.cpp"]
)

cc_binary(
	name  = "81SearchinRotatedSortedArrayIITest",
	srcs  = ["81.SearchinRotatedSortedArrayIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["81SearchinRotatedSortedArrayII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "154FindMinimuminRotatedSortedArrayII",
	hdrs = ["154.FindMinimuminRotatedSortedArrayII.h"],
	srcs = ["154.FindMinimuminRotatedSortedArrayII.cpp"]
)

cc_binary(
	name  = "154FindMinimuminRotatedSortedArrayIITest",
	srcs  = ["154.FindMinimuminRotatedSortedArrayIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["154FindMinimuminRotatedSortedArrayII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "540SingleElementinaSortedArray",
	hdrs = ["540.SingleElementinaSortedArray.h"],
	srcs = ["540.SingleElementinaSortedArray.cpp"]
)

cc_binary(
	name  = "540SingleElementinaSortedArrayTest",
	srcs  = ["540.SingleElementinaSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["540SingleElementinaSortedArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "4MedianofTwoSortedArrays",
	hdrs = ["4.MedianofTwoSortedArrays.h"],
	srcs = ["4.MedianofTwoSortedArrays.cpp"]
)

cc_binary(
	name  = "4MedianofTwoSortedArraysTest",
	srcs  = ["4.MedianofTwoSortedArraysTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["4MedianofTwoSortedArrays",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "34FindFirstandLastPositionofElementinSortedArra",
	hdrs = ["34.FindFirstandLastPositionofElementinSortedArra.h"],
	srcs = ["34.FindFirstandLastPositionofElementinSortedArra.cpp"]
)

cc_binary(
	name  = "34FindFirstandLastPositionofElementinSortedArraTest",
	srcs  = ["34.FindFirstandLastPositionofElementinSortedArraTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["34FindFirstandLastPositionofElementinSortedArra",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "35SearchInsertPosition",
	hdrs = ["35.SearchInsertPosition.h"],
	srcs = ["35.SearchInsertPosition.cpp"]
)

cc_binary(
	name  = "35SearchInsertPositionTest",
	srcs  = ["35.SearchInsertPositionTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["35SearchInsertPosition",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "153FindMinimuminRotatedSortedArray",
	hdrs = ["153.FindMinimuminRotatedSortedArray.h"],
	srcs = ["153.FindMinimuminRotatedSortedArray.cpp"]
)

cc_binary(
	name  = "153FindMinimuminRotatedSortedArrayTest",
	srcs  = ["153.FindMinimuminRotatedSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["153FindMinimuminRotatedSortedArray",
			 "@googletest//:gtest_main"],
)