cc_library(
	name = "69Sqrtx",
	hdrs = ["69.Sqrt(x).h"],
	srcs = ["69.Sqrt(x).cpp"]
)

cc_binary(
	name  = "69SqrtxTest",
	srcs  = ["69.Sqrt(x)Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["69Sqrtx",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "34FindFirstandLastPositionofElementinSortedArray",
	hdrs = ["34.FindFirstandLastPositionofElementinSortedArray.h"],
	srcs = ["34.FindFirstandLastPositionofElementinSortedArray.cpp"]
)

cc_binary(
	name  = "34FindFirstandLastPositionofElementinSortedArrayTest",
	srcs  = ["34.FindFirstandLastPositionofElementinSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["34FindFirstandLastPositionofElementinSortedArray",
			 "@googletest//:gtest_main"],
)