cc_library(
	name = "69Sqrtx",
	hdrs = ["69.Sqrt(x).h"],
	srcs = ["69.Sqrt(x).cpp"]
)

cc_binary(
	name  = "69SqrtxTest",
	srcs  = ["69.Sqrt(x)Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["69Sqrtx",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "34FindFirstandLastPositionofElementinSortedArray",
	hdrs = ["34.FindFirstandLastPositionofElementinSortedArray.h"],
	srcs = ["34.FindFirstandLastPositionofElementinSortedArray.cpp"]
)

cc_binary(
	name  = "34FindFirstandLastPositionofElementinSortedArrayTest",
	srcs  = ["34.FindFirstandLastPositionofElementinSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["34FindFirstandLastPositionofElementinSortedArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "81SearchinRotatedSortedArrayII",
	hdrs = ["81.SearchinRotatedSortedArrayII.h"],
	srcs = ["81.SearchinRotatedSortedArrayII.cpp"]
)

cc_binary(
	name  = "81SearchinRotatedSortedArrayIITest",
	srcs  = ["81.SearchinRotatedSortedArrayIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["81SearchinRotatedSortedArrayII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "154FindMinimuminRotatedSortedArrayII",
	hdrs = ["154.FindMinimuminRotatedSortedArrayII.h"],
	srcs = ["154.FindMinimuminRotatedSortedArrayII.cpp"]
)

cc_binary(
	name  = "154FindMinimuminRotatedSortedArrayIITest",
	srcs  = ["154.FindMinimuminRotatedSortedArrayIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["154FindMinimuminRotatedSortedArrayII",
			 "@googletest//:gtest_main"],
)