cc_library(
	name = "70ClimbingStairs",
	hdrs = ["70.ClimbingStairs.h"],
	srcs = ["70.ClimbingStairs.cpp"]
)

cc_binary(
	name  = "70ClimbingStairsTest",
	srcs  = ["70.ClimbingStairsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["70ClimbingStairs",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "198HouseRobber",
	hdrs = ["198.HouseRobber.h"],
	srcs = ["198.HouseRobber.cpp"]
)

cc_binary(
	name  = "198HouseRobberTest",
	srcs  = ["198.HouseRobberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["198HouseRobber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "413ArithmeticSlices",
	hdrs = ["413.ArithmeticSlices.h"],
	srcs = ["413.ArithmeticSlices.cpp"]
)

cc_binary(
	name  = "413ArithmeticSlicesTest",
	srcs  = ["413.ArithmeticSlicesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["413ArithmeticSlices",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "64MinimumPathSum",
	hdrs = ["64.MinimumPathSum.h"],
	srcs = ["64.MinimumPathSum.cpp"]
)

cc_binary(
	name  = "64MinimumPathSumTest",
	srcs  = ["64.MinimumPathSumTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["64MinimumPathSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "54201Matrix",
	hdrs = ["542.01Matrix.h"],
	srcs = ["542.01Matrix.cpp"]
)

cc_binary(
	name  = "54201MatrixTest",
	srcs  = ["542.01MatrixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["54201Matrix",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "221MaximalSquare",
	hdrs = ["221.MaximalSquare.h"],
	srcs = ["221.MaximalSquare.cpp"]
)

cc_binary(
	name  = "221MaximalSquareTest",
	srcs  = ["221.MaximalSquareTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["221MaximalSquare",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "85MaximalRectangle",
	hdrs = ["85.MaximalRectangle.h"],
	srcs = ["85.MaximalRectangle.cpp"]
)

cc_binary(
	name  = "85MaximalRectangleTest",
	srcs  = ["85.MaximalRectangleTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["85MaximalRectangle",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1137NthTribonacciNumber",
	hdrs = ["1137.NthTribonacciNumber.h"],
	srcs = ["1137.NthTribonacciNumber.cpp"]
)

cc_binary(
	name  = "1137NthTribonacciNumberTest",
	srcs  = ["1137.NthTribonacciNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1137NthTribonacciNumber",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "279PerfectSquares",
	hdrs = ["279.PerfectSquares.h"],
	srcs = ["279.PerfectSquares.cpp"]
)

cc_binary(
	name  = "279PerfectSquaresTest",
	srcs  = ["279.PerfectSquaresTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["279PerfectSquares",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "91DecodeWays",
	hdrs = ["91.DecodeWays.h"],
	srcs = ["91.DecodeWays.cpp"]
)

cc_binary(
	name  = "91DecodeWaysTest",
	srcs  = ["91.DecodeWaysTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["91DecodeWays",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "139WordBreak",
	hdrs = ["139.WordBreak.h"],
	srcs = ["139.WordBreak.cpp"]
)

cc_binary(
	name  = "139WordBreakTest",
	srcs  = ["139.WordBreakTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["139WordBreak",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "300LongestIncreasingSubsequence",
	hdrs = ["300.LongestIncreasingSubsequence.h"],
	srcs = ["300.LongestIncreasingSubsequence.cpp"]
)

cc_binary(
	name  = "300LongestIncreasingSubsequenceTest",
	srcs  = ["300.LongestIncreasingSubsequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["300LongestIncreasingSubsequence",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "416PartitionEqualSubsetSum",
	hdrs = ["416.PartitionEqualSubsetSum.h"],
	srcs = ["416.PartitionEqualSubsetSum.cpp"]
)

cc_binary(
	name  = "416PartitionEqualSubsetSumTest",
	srcs  = ["416.PartitionEqualSubsetSumTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["416PartitionEqualSubsetSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1143LongestCommonSubsequence",
	hdrs = ["1143.LongestCommonSubsequence.h"],
	srcs = ["1143.LongestCommonSubsequence.cpp"]
)

cc_binary(
	name  = "1143LongestCommonSubsequenceTest",
	srcs  = ["1143.LongestCommonSubsequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1143LongestCommonSubsequence",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "474OnesandZeroes",
	hdrs = ["474.OnesandZeroes.h"],
	srcs = ["474.OnesandZeroes.cpp"]
)

cc_binary(
	name  = "474OnesandZeroesTest",
	srcs  = ["474.OnesandZeroesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["474OnesandZeroes",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "322CoinChange",
	hdrs = ["322.CoinChange.h"],
	srcs = ["322.CoinChange.cpp"]
)

cc_binary(
	name  = "322CoinChangeTest",
	srcs  = ["322.CoinChangeTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["322CoinChange",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "72EditDistance",
	hdrs = ["72.EditDistance.h"],
	srcs = ["72.EditDistance.cpp"]
)

cc_binary(
	name  = "72EditDistanceTest",
	srcs  = ["72.EditDistanceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["72EditDistance",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "6502KeysKeyboard",
	hdrs = ["650.2KeysKeyboard.h"],
	srcs = ["650.2KeysKeyboard.cpp"]
)

cc_binary(
	name  = "6502KeysKeyboardTest",
	srcs  = ["650.2KeysKeyboardTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["6502KeysKeyboard",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "10RegularExpressionMatching",
	hdrs = ["10.RegularExpressionMatching.h"],
	srcs = ["10.RegularExpressionMatching.cpp"]
)

cc_binary(
	name  = "10RegularExpressionMatchingTest",
	srcs  = ["10.RegularExpressionMatchingTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["10RegularExpressionMatching",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "188BestTimetoBuyandSellStockIV",
	hdrs = ["188.BestTimetoBuyandSellStockIV.h"],
	srcs = ["188.BestTimetoBuyandSellStockIV.cpp"]
)

cc_binary(
	name  = "188BestTimetoBuyandSellStockIVTest",
	srcs  = ["188.BestTimetoBuyandSellStockIVTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["188BestTimetoBuyandSellStockIV",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "309BestTimetoBuyandSellStockwithCooldown",
	hdrs = ["309.BestTimetoBuyandSellStockwithCooldown.h"],
	srcs = ["309.BestTimetoBuyandSellStockwithCooldown.cpp"]
)

cc_binary(
	name  = "309BestTimetoBuyandSellStockwithCooldownTest",
	srcs  = ["309.BestTimetoBuyandSellStockwithCooldownTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["309BestTimetoBuyandSellStockwithCooldown",
			 "@googletest//:gtest_main"],
)
