cc_library(
	name = "70ClimbingStairs",
	hdrs = ["70.ClimbingStairs.h"],
	srcs = ["70.ClimbingStairs.cpp"]
)

cc_binary(
	name  = "70ClimbingStairsTest",
	srcs  = ["70.ClimbingStairsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["70ClimbingStairs",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "198HouseRobber",
	hdrs = ["198.HouseRobber.h"],
	srcs = ["198.HouseRobber.cpp"]
)

cc_binary(
	name  = "198HouseRobberTest",
	srcs  = ["198.HouseRobberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["198HouseRobber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "413ArithmeticSlices",
	hdrs = ["413.ArithmeticSlices.h"],
	srcs = ["413.ArithmeticSlices.cpp"]
)

cc_binary(
	name  = "413ArithmeticSlicesTest",
	srcs  = ["413.ArithmeticSlicesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["413ArithmeticSlices",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "64MinimumPathSum",
	hdrs = ["64.MinimumPathSum.h"],
	srcs = ["64.MinimumPathSum.cpp"]
)

cc_binary(
	name  = "64MinimumPathSumTest",
	srcs  = ["64.MinimumPathSumTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["64MinimumPathSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "54201Matrix",
	hdrs = ["542.01Matrix.h"],
	srcs = ["542.01Matrix.cpp"]
)

cc_binary(
	name  = "54201MatrixTest",
	srcs  = ["542.01MatrixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["54201Matrix",
			 "@googletest//:gtest_main"],
)