cc_library(
	name  = "128LongestConsecutiveSequence",
    hdrs  = ["128.LongestConsecutiveSequence.h"], 
	srcs  = ["128.LongestConsecutiveSequence.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "128LongestConsecutiveSequenceTest",
	srcs  = ["128.LongestConsecutiveSequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["128LongestConsecutiveSequence",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "149MaxPointsonaLine",
    hdrs  = ["149.MaxPointsonaLine.h"], 
	srcs  = ["149.MaxPointsonaLine.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "149MaxPointsonaLineTest",
	srcs  = ["149.MaxPointsonaLineTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["149MaxPointsonaLine",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "332ReconstructItinerary",
    hdrs  = ["332.ReconstructItinerary.h"], 
	srcs  = ["332.ReconstructItinerary.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "332ReconstructItineraryTest",
	srcs  = ["332.ReconstructItineraryTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["332ReconstructItinerary",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "303RangeSumQueryImmutable",
    hdrs  = ["303.RangeSumQuery-Immutable.h"], 
	srcs  = ["303.RangeSumQuery-Immutable.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "303RangeSumQueryImmutableTest",
	srcs  = ["303.RangeSumQuery-ImmutableTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["303RangeSumQueryImmutable",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "304RangeSumQuery2DImmutable",
    hdrs  = ["304.RangeSumQuery2D-Immutable.h"], 
	srcs  = ["304.RangeSumQuery2D-Immutable.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "304RangeSumQuery2DImmutableTest",
	srcs  = ["304.RangeSumQuery2D-ImmutableTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["304RangeSumQuery2DImmutable",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "560SubarraySumEqualsK",
    hdrs  = ["560.SubarraySumEqualsK.h"], 
	srcs  = ["560.SubarraySumEqualsK.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "560SubarraySumEqualsKTest",
	srcs  = ["560.SubarraySumEqualsKTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["560SubarraySumEqualsK",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "217ContainsDuplicate",
    hdrs  = ["217.ContainsDuplicate.h"], 
	srcs  = ["217.ContainsDuplicate.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "217ContainsDuplicateTest",
	srcs  = ["217.ContainsDuplicateTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["217ContainsDuplicate",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "503NextGreaterElementII",
    hdrs  = ["503.NextGreaterElementII.h"], 
	srcs  = ["503.NextGreaterElementII.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "503NextGreaterElementIITest",
	srcs  = ["503.NextGreaterElementIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["503NextGreaterElementII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "697DegreeofanArray",
    hdrs  = ["697.DegreeofanArray.h"], 
	srcs  = ["697.DegreeofanArray.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "697DegreeofanArrayTest",
	srcs  = ["697.DegreeofanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["697DegreeofanArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "594LongestHarmoniousSubsequence",
    hdrs  = ["594.LongestHarmoniousSubsequence.h"], 
	srcs  = ["594.LongestHarmoniousSubsequence.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "594LongestHarmoniousSubsequenceTest",
	srcs  = ["594.LongestHarmoniousSubsequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["594LongestHarmoniousSubsequence",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "287FindtheDuplicateNumber",
    hdrs  = ["287.FindtheDuplicateNumber.h"], 
	srcs  = ["287.FindtheDuplicateNumber.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "287FindtheDuplicateNumberTest",
	srcs  = ["287.FindtheDuplicateNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["287FindtheDuplicateNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "313SuperUglyNumber",
    hdrs  = ["313.SuperUglyNumber.h"], 
	srcs  = ["313.SuperUglyNumber.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "313SuperUglyNumberTest",
	srcs  = ["313.SuperUglyNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["313SuperUglyNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "307RangeSumQueryMutable",
    hdrs  = ["307.RangeSumQuery-Mutable.h"], 
	srcs  = ["307.RangeSumQuery-Mutable.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "307RangeSumQueryMutableTest",
	srcs  = ["307.RangeSumQuery-MutableTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["307RangeSumQueryMutable",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "49GroupAnagrams",
    hdrs  = ["49.GroupAnagrams.h"], 
	srcs  = ["49.GroupAnagrams.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "49GroupAnagramsTest",
	srcs  = ["49.GroupAnagramsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["49GroupAnagrams",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "219ContainsDuplicateII",
    hdrs  = ["219.ContainsDuplicateII.h"], 
	srcs  = ["219.ContainsDuplicateII.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "219ContainsDuplicateIITest",
	srcs  = ["219.ContainsDuplicateIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["219ContainsDuplicateII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "220ContainsDuplicateIII",
    hdrs  = ["220.ContainsDuplicateIII.h"], 
	srcs  = ["220.ContainsDuplicateIII.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "220ContainsDuplicateIIITest",
	srcs  = ["220.ContainsDuplicateIIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["220ContainsDuplicateIII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "290WordPattern",
    hdrs  = ["290.WordPattern.h"], 
	srcs  = ["290.WordPattern.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "290WordPatternTest",
	srcs  = ["290.WordPatternTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["290WordPattern",
			 "@googletest//:gtest_main"],
)