cc_library(
	name  = "128LongestConsecutiveSequence",
    hdrs  = ["128.LongestConsecutiveSequence.h"], 
	srcs  = ["128.LongestConsecutiveSequence.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "128LongestConsecutiveSequenceTest",
	srcs  = ["128.LongestConsecutiveSequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["128LongestConsecutiveSequence",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "149MaxPointsonaLine",
    hdrs  = ["149.MaxPointsonaLine.h"], 
	srcs  = ["149.MaxPointsonaLine.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "149MaxPointsonaLineTest",
	srcs  = ["149.MaxPointsonaLineTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["149MaxPointsonaLine",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "332ReconstructItinerary",
    hdrs  = ["332.ReconstructItinerary.h"], 
	srcs  = ["332.ReconstructItinerary.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "332ReconstructItineraryTest",
	srcs  = ["332.ReconstructItineraryTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["332ReconstructItinerary",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "303RangeSumQueryImmutable",
    hdrs  = ["303.RangeSumQuery-Immutable.h"], 
	srcs  = ["303.RangeSumQuery-Immutable.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "303RangeSumQueryImmutableTest",
	srcs  = ["303.RangeSumQuery-ImmutableTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["303RangeSumQueryImmutable",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "304RangeSumQuery2DImmutable",
    hdrs  = ["304.RangeSumQuery2D-Immutable.h"], 
	srcs  = ["304.RangeSumQuery2D-Immutable.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "304RangeSumQuery2DImmutableTest",
	srcs  = ["304.RangeSumQuery2D-ImmutableTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["304RangeSumQuery2DImmutable",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "560SubarraySumEqualsK",
    hdrs  = ["560.SubarraySumEqualsK.h"], 
	srcs  = ["560.SubarraySumEqualsK.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "560SubarraySumEqualsKTest",
	srcs  = ["560.SubarraySumEqualsKTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["560SubarraySumEqualsK",
			 "@googletest//:gtest_main"],
)

cc_library(
	name  = "217ContainsDuplicate",
    hdrs  = ["217.ContainsDuplicate.h"], 
	srcs  = ["217.ContainsDuplicate.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "217ContainsDuplicateTest",
	srcs  = ["217.ContainsDuplicateTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["217ContainsDuplicate",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "503NextGreaterElementII",
    hdrs  = ["503.NextGreaterElementII.h"], 
	srcs  = ["503.NextGreaterElementII.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "503NextGreaterElementIITest",
	srcs  = ["503.NextGreaterElementIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["503NextGreaterElementII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "697DegreeofanArray",
    hdrs  = ["697.DegreeofanArray.h"], 
	srcs  = ["697.DegreeofanArray.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "697DegreeofanArrayTest",
	srcs  = ["697.DegreeofanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["697DegreeofanArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name  = "594LongestHarmoniousSubsequence",
    hdrs  = ["594.LongestHarmoniousSubsequence.h"], 
	srcs  = ["594.LongestHarmoniousSubsequence.cpp"],
	copts = ["-std=c++11"],
)

cc_binary(
	name  = "594LongestHarmoniousSubsequenceTest",
	srcs  = ["594.LongestHarmoniousSubsequenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["594LongestHarmoniousSubsequence",
			 "@googletest//:gtest_main"],
)