cc_binary(
    name  = "fcntl_getfl",
    srcs  = ["fcntl_getfl.cc"],
    copts = ["-std=c++11"],
    deps  = ["//lib/err:myerr"]
    copts = ["-std=c++11"],
)

cc_binary(
    name = "set_file_flag",
    srcs = ["setflag.cc"],
    copts = ["-std=c++11"],
    deps = ["//lib/file:myfcntl"],
)