cc_binary(
	name  = "scopeguard_test",
	srcs  = ["scopeguard_test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["//lib/comm/class:scopeguard",
			 "@googletest//:gtest_main"],
)

cc_binary(
	name  = "singleton_test",
	srcs  = ["singleton_test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["//lib/comm/class:singleton",
			 "@googletest//:gtest_main"],
)