cc_library(
	name = "14_LongestCommonPrefix",
	hdrs = ["14.LongestCommonPrefix.h"],
	srcs = ["14.LongestCommonPrefix.cpp"]
)

cc_binary(
	name  = "LongestCommonPrefixTest",
	srcs  = ["14.LongestCommonPrefixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["14_LongestCommonPrefix",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "3LongestSubStringWithoutRepeat",
	hdrs = ["3.LongestSubstringWithoutRepeatingCharacters.h"],
	srcs = ["3.LongestSubstringWithoutRepeatingCharacters.cpp"]
)


cc_binary(
	name  = "3LongestSubStringWithoutRepeatTest",
	srcs  = ["3.LongestSubstringWithoutRepeatingCharactersTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["3LongestSubStringWithoutRepeat",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "5LongestPalindromicSubstring",
	hdrs = ["5.LongestPalindromicSubstring.h"],
	srcs = ["5.LongestPalindromicSubstring.cpp"]
)


cc_binary(
	name  = "5LongestPalindromicSubstringTest",
	srcs  = ["5.LongestPalindromicSubstringTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["5LongestPalindromicSubstring",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "zigzagConversion",
	hdrs = ["6.ZigzagConversion.h"],
	srcs = ["6.ZigzagConversion.cpp"]
)


cc_binary(
	name  = "zigzagConversionTest",
	srcs  = ["6.ZigzagConversionTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["zigzagConversion",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "394DecodeString",
	hdrs = ["394.DecodeString.h"],
	srcs = ["394.DecodeString.cpp"]
)


cc_binary(
	name  = "394DecodeStringTest",
	srcs  = ["394.DecodeStringTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["394DecodeString",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "8StringtoIntegerATOI",
	hdrs = ["8.StringtoInteger(atoi).h"],
	srcs = ["8.StringtoInteger(atoi).cpp"]
)


cc_binary(
	name  = "8StringtoIntegerATOITest",
	srcs  = ["8.StringtoInteger(atoi)Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["8StringtoIntegerATOI",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "13RomantoInteger",
	hdrs = ["13.RomantoInteger.h"],
	srcs = ["13.RomantoInteger.cpp"]
)


cc_binary(
	name  = "13RomantoIntegerTest",
	srcs  = ["13.RomantoIntegerTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["13RomantoInteger",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "131PalindromePartitioning",
	hdrs = ["131.PalindromePartitioning.h"],
	srcs = ["131.PalindromePartitioning.cpp"]
)


cc_binary(
	name  = "131PalindromePartitioningTest",
	srcs  = ["131.PalindromePartitioningTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["131PalindromePartitioning",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "953VerifyinganAlienDictionary",
	hdrs = ["953.VerifyinganAlienDictionary.h"],
	srcs = ["953.VerifyinganAlienDictionary.cpp"]
)


cc_binary(
	name  = "953VerifyinganAlienDictionaryTest",
	srcs  = ["953.VerifyinganAlienDictionaryTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["953VerifyinganAlienDictionary",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "242ValidAnagram",
	hdrs = ["242.ValidAnagram.h"],
	srcs = ["242.ValidAnagram.cpp"]
)


cc_binary(
	name  = "242ValidAnagramTest",
	srcs  = ["242.ValidAnagramTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["242ValidAnagram",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "205IsomorphicStrings",
	hdrs = ["205.IsomorphicStrings.h"],
	srcs = ["205.IsomorphicStrings.cpp"]
)


cc_binary(
	name  = "205IsomorphicStringsTest",
	srcs  = ["205.IsomorphicStringsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["205IsomorphicStrings",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "647PalindromicSubstrings",
	hdrs = ["647.PalindromicSubstrings.h"],
	srcs = ["647.PalindromicSubstrings.cpp"]
)


cc_binary(
	name  = "647PalindromicSubstringsTest",
	srcs  = ["647.PalindromicSubstringsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["647PalindromicSubstrings",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "696CountBinarySubstrings",
	hdrs = ["696.CountBinarySubstrings.h"],
	srcs = ["696.CountBinarySubstrings.cpp"]
)


cc_binary(
	name  = "696CountBinarySubstringsTest",
	srcs  = ["696.CountBinarySubstringsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["696CountBinarySubstrings",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "227BasicCalculatorII",
	hdrs = ["227.BasicCalculatorII.h"],
	srcs = ["227.BasicCalculatorII.cpp"]
)


cc_binary(
	name  = "227BasicCalculatorIITest",
	srcs  = ["227.BasicCalculatorIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["227BasicCalculatorII",
			 "@googletest//:gtest_main"],
)



cc_library(
	name = "28FindtheIndexoftheFirstOccurrenceinaString",
	hdrs = ["28.FindtheIndexoftheFirstOccurrenceinaString.h"],
	srcs = ["28.FindtheIndexoftheFirstOccurrenceinaString.cpp"]
)


cc_binary(
	name  = "28FindtheIndexoftheFirstOccurrenceinaStringTest",
	srcs  = ["28.FindtheIndexoftheFirstOccurrenceinaStringTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["28FindtheIndexoftheFirstOccurrenceinaString",
			 "@googletest//:gtest_main"],
)