cc_library(
    name = "term",
    hdrs = ["term.h"],
    srcs = ["term.cc"],
    deps = ["//lib/err:myerr",
            "//lib/condition:condition",
        ],
    copts = ["-std=c++11"],
    visibility = ["//visibility:public"]
)