cc_library(
	name = "146LRUCache",
	hdrs = ["146.LRUCache.h"],
	srcs = ["146.LRUCache.cpp"]
)

cc_binary(
	name  = "146LRUCacheTest",
	srcs  = ["146.LRUCacheTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["146LRUCache",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "460LFUCache",
	hdrs = ["460.LFUCache.h"],
	srcs = ["460.LFUCache.cpp"]
)

cc_binary(
	name  = "460LFUCacheTest",
	srcs  = ["460.LFUCacheTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["460LFUCache",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "380InsertDeleteGetRandomO1",
	hdrs = ["380.InsertDeleteGetRandomO1.h"],
	srcs = ["380.InsertDeleteGetRandomO1.cpp"]
)

cc_binary(
	name  = "380InsertDeleteGetRandomO1Test",
	srcs  = ["380.InsertDeleteGetRandomO1Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["380InsertDeleteGetRandomO1",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "432AllOoneDataStructure",
	hdrs = ["432.AllOoneDataStructure.h"],
	srcs = ["432.AllOoneDataStructure.cpp"]
)

cc_binary(
	name  = "432AllOoneDataStructureTest",
	srcs  = ["432.AllOoneDataStructureTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["432AllOoneDataStructure",
			 "@googletest//:gtest_main"],
)