cc_library(
	name = "146LRUCache",
	hdrs = ["146.LRUCache.h"],
	srcs = ["146.LRUCache.cpp"]
)

cc_binary(
	name  = "146LRUCacheTest",
	srcs  = ["146.LRUCacheTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["146LRUCache",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "460LFUCache",
	hdrs = ["460.LFUCache.h"],
	srcs = ["460.LFUCache.cpp"]
)

cc_binary(
	name  = "460LFUCacheTest",
	srcs  = ["460.LFUCacheTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["460LFUCache",
			 "@googletest//:gtest_main"],
)