cc_binary(
	name="processFork",
	srcs=["processFork.cc"],
	copts = ["-std=c++11"],
)

cc_binary(
    name = "getpid",
    srcs = ["getpid.cc"],
	deps = ["//lib/term:term"],
	copts = ["-std=c++11"],
)

cc_binary(
    name = "process_chdir",
    srcs = ["process_dir.cc"],
	deps = ["//lib/term:term"],
	copts = ["-std=c++11"],
)