

cc_library(
	name = "231PowerofTwo",
	hdrs = ["231.PowerofTwo.h"],
	srcs = ["231.PowerofTwo.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "231PowerofTwoTest",
	srcs  = ["231.PowerofTwoTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["231PowerofTwo",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "1015SmallestIntegerDivisiblebyK",
	hdrs = ["1015.SmallestIntegerDivisiblebyK.h"],
	srcs = ["1015.SmallestIntegerDivisiblebyK.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "1015SmallestIntegerDivisiblebyKTest",
	srcs  = ["1015.SmallestIntegerDivisiblebyKTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1015SmallestIntegerDivisiblebyK",
			 "@googletest//:gtest_main"],
)