

cc_library(
	name = "231PowerofTwo",
	hdrs = ["231.PowerofTwo.h"],
	srcs = ["231.PowerofTwo.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "231PowerofTwoTest",
	srcs  = ["231.PowerofTwoTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["231PowerofTwo",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "1015SmallestIntegerDivisiblebyK",
	hdrs = ["1015.SmallestIntegerDivisiblebyK.h"],
	srcs = ["1015.SmallestIntegerDivisiblebyK.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "1015SmallestIntegerDivisiblebyKTest",
	srcs  = ["1015.SmallestIntegerDivisiblebyKTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1015SmallestIntegerDivisiblebyK",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1009ComplementofBase10Integer",
	hdrs = ["1009.ComplementofBase10Integer.h"],
	srcs = ["1009.ComplementofBase10Integer.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "1009ComplementofBase10IntegerTest",
	srcs  = ["1009.ComplementofBase10IntegerTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1009ComplementofBase10Integer",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "12IntegerToRoman",
	hdrs = ["12.IntegerToRoman.h"],
	srcs = ["12.IntegerToRoman.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "12IntegerToRomanTest",
	srcs  = ["12.IntegerToRomanTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["12IntegerToRoman",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "204CountPrimes",
	hdrs = ["204.CountPrimes.h"],
	srcs = ["204.CountPrimes.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "204CountPrimesTest",
	srcs  = ["204.CountPrimesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["204CountPrimes",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "504Base7",
	hdrs = ["504.Base7.h"],
	srcs = ["504.Base7.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "504Base7Test",
	srcs  = ["504.Base7Test.cpp"],
	copts = ["-std=c++11"],
	deps  = ["504Base7",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "172FactorialTrailingZeroes",
	hdrs = ["172.FactorialTrailingZeroes.h"],
	srcs = ["172.FactorialTrailingZeroes.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "172FactorialTrailingZeroesTest",
	srcs  = ["172.FactorialTrailingZeroesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["172FactorialTrailingZeroes",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "415AddStrings",
	hdrs = ["415.AddStrings.h"],
	srcs = ["415.AddStrings.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "415AddStringsTest",
	srcs  = ["415.AddStringsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["415AddStrings",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "326PowerofThree",
	hdrs = ["326.PowerofThree.h"],
	srcs = ["326.PowerofThree.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "326PowerofThreeTest",
	srcs  = ["326.PowerofThreeTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["326PowerofThree",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "384ShuffleanArray",
	hdrs = ["384.ShuffleanArray.h"],
	srcs = ["384.ShuffleanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "384ShuffleanArrayTest",
	srcs  = ["384.ShuffleanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["384ShuffleanArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "528RandomPickwithWeight",
	hdrs = ["528.RandomPickwithWeight.h"],
	srcs = ["528.RandomPickwithWeight.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "528RandomPickwithWeightTest",
	srcs  = ["528.RandomPickwithWeightTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["528RandomPickwithWeight",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "168ExcelSheetColumnTitle",
	hdrs = ["168.ExcelSheetColumnTitle.h"],
	srcs = ["168.ExcelSheetColumnTitle.cpp"],

cc_library(
	name = "382LinkedListRandomNode",
	hdrs = ["382.LinkedListRandomNode.h"],
	srcs = ["382.LinkedListRandomNode.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "168ExcelSheetColumnTitleTest",
	srcs  = ["168.ExcelSheetColumnTitleTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["168ExcelSheetColumnTitle",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "67AddBinary",
	hdrs = ["67.AddBinary.h"],
	srcs = ["67.AddBinary.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "67AddBinaryTest",
	srcs  = ["67.AddBinaryTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["67AddBinary",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "238ProductofArrayExceptSel",
	hdrs = ["238.ProductofArrayExceptSel.h"],
	srcs = ["238.ProductofArrayExceptSel.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "238ProductofArrayExceptSelTest",
	srcs  = ["238.ProductofArrayExceptSelTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["238ProductofArrayExceptSel",
			 "@googletest//:gtest_main"],
)


cc_binary(
	name  = "382LinkedListRandomNodeTest",
	srcs  = ["382.LinkedListRandomNodeTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["382LinkedListRandomNode",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "169MajorityElement",
	hdrs = ["169.MajorityElement.h"],
	srcs = ["169.MajorityElement.cpp"],
    copts = ["-std=c++11"],
)


cc_binary(
	name  = "169MajorityElementTest",
	srcs  = ["169.MajorityElementTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["382LinkedListRandomNode",
			 "@googletest//:gtest_main"],
)