cc_library(
    name = "singleton",
    srcs = ["singleton.h"],
    copts = ["-std=c++11"],
    deps = [
        "//lib/comm/class:nocopyable",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "factory",
    srcs = ["factory.h"],
    copts = ["-std=c++11"],
    deps = [
        "//lib/comm/class:nocopyable",
    ],
    visibility = ["//visibility:public"],
)


cc_library(
    name = "chain",
    srcs = ["chain.h"],
    copts = ["-std=c++11"],
    deps = [
        "//lib/comm/class:nocopyable",
    ],
    visibility = ["//visibility:public"],
)