cc_library(
	name = "linkComm",
	hdrs = ["linkcomm.h"],
	srcs = ["linkcomm.cpp"],
	visibility = ["//visibility:public"],
)

cc_library(
	name = "AddTwoNum",
	hdrs = ["2.AddTwoNumbers.h"],
	srcs = ["2.AddTwoNumbers.cpp"],
    copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "AddTwoNumTest",
	srcs  = ["2.AddTwoNumberstest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["AddTwoNum",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "143ReorderList",
	hdrs = ["143.ReorderList.h"],
	srcs = ["143.ReorderList.cpp"],
    copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "143ReorderListTest",
	srcs  = ["143.ReorderListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["143ReorderList",
			 "@googletest//:gtest_main"],
)



cc_library(
	name = "142LinkedListCycleII",
	hdrs = ["142.LinkedListCycleII.h"],
	srcs = ["142.LinkedListCycleII.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "142LinkedListCycleIITest",
	srcs  = ["142.LinkedListCycleIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["142LinkedListCycleII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "206ReverseLinkedList",
	hdrs = ["206.ReverseLinkedList.h"],
	srcs = ["206.ReverseLinkedList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "206ReverseLinkedListTest",
	srcs  = ["206.ReverseLinkedListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["206ReverseLinkedList",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "21MergeTwoSortedLists",
	hdrs = ["21.MergeTwoSortedLists.h"],
	srcs = ["21.MergeTwoSortedLists.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "21MergeTwoSortedListsTest",
	srcs  = ["21.MergeTwoSortedListsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["21MergeTwoSortedLists",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "24SwapNodesinPairs",
	hdrs = ["24.SwapNodesinPairs.h"],
	srcs = ["24.SwapNodesinPairs.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "24SwapNodesinPairsTest",
	srcs  = ["24.SwapNodesinPairsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["24SwapNodesinPairs",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "160IntersectionofTwoLinkedLists",
	hdrs = ["160.IntersectionofTwoLinkedLists.h"],
	srcs = ["160.IntersectionofTwoLinkedLists.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "160IntersectionofTwoLinkedListsTest",
	srcs  = ["160.IntersectionofTwoLinkedListsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["160IntersectionofTwoLinkedLists",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "234PalindromeLinkedList",
	hdrs = ["234.PalindromeLinkedList.h"],
	srcs = ["234.PalindromeLinkedList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "234PalindromeLinkedListTest",
	srcs  = ["234.PalindromeLinkedListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["234PalindromeLinkedList",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "83RemoveDuplicatesfromSortedList",
	hdrs = ["83.RemoveDuplicatesfromSortedList.h"],
	srcs = ["83.RemoveDuplicatesfromSortedList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "83RemoveDuplicatesfromSortedListTest",
	srcs  = ["83.RemoveDuplicatesfromSortedListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["83RemoveDuplicatesfromSortedList",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "328OddEvenLinkedList",
	hdrs = ["328.OddEvenLinkedList.h"],
	srcs = ["328.OddEvenLinkedList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "328OddEvenLinkedListTest",
	srcs  = ["328.OddEvenLinkedListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["328OddEvenLinkedList",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "19RemoveNthNodeFromEndofList",
	hdrs = ["19.RemoveNthNodeFromEndofList.h"],
	srcs = ["19.RemoveNthNodeFromEndofList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "19RemoveNthNodeFromEndofListTest",
	srcs  = ["19.RemoveNthNodeFromEndofListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["19RemoveNthNodeFromEndofList",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "148SortList",
	hdrs = ["148.SortList.h"],
	srcs = ["148.SortList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "148SortListTest",
	srcs  = ["148.SortListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["148SortList",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "138CopyListwithRandomPointer",
	hdrs = ["138.CopyListwithRandomPointer.h"],
	srcs = ["138.CopyListwithRandomPointer.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "138CopyListwithRandomPointerTest",
	srcs  = ["138.CopyListwithRandomPointerTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["138CopyListwithRandomPointer",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "61RotateList",
	hdrs = ["61.RotateList.h"],
	srcs = ["61.RotateList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "61RotateListTest",
	srcs  = ["61.RotateListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["61RotateList",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "82RemoveDuplicatesfromSortedListII",
	hdrs = ["82.RemoveDuplicatesfromSortedListII.h"],
	srcs = ["82.RemoveDuplicatesfromSortedListII.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "82RemoveDuplicatesfromSortedListIITest",
	srcs  = ["82.RemoveDuplicatesfromSortedListIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["82RemoveDuplicatesfromSortedListII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "86PartitionList",
	hdrs = ["86.PartitionList.h"],
	srcs = ["86.PartitionList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "86PartitionListTest",
	srcs  = ["86.PartitionListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["86PartitionList",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "92ReverseLinkedListII",
	hdrs = ["92.ReverseLinkedListII.h"],
	srcs = ["92.ReverseLinkedListII.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "92ReverseLinkedListIITest",
	srcs  = ["92.ReverseLinkedListIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["92ReverseLinkedListII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "141LinkedListCycle",
	hdrs = ["141.LinkedListCycle.h"],
	srcs = ["141.LinkedListCycle.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "141LinkedListCycleTest",
	srcs  = ["141.LinkedListCycleTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["141LinkedListCycle",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "147InsertionSortList",
	hdrs = ["147.InsertionSortList.h"],
	srcs = ["147.InsertionSortList.cpp"],
	copts = ["-std=c++11"],
	deps  = ["linkComm"],
)

cc_binary(
	name  = "147InsertionSortListTest",
	srcs  = ["147.InsertionSortListTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["147InsertionSortList",
			 "@googletest//:gtest_main"],
)