cc_library(
	name = "461HammingDistance",
	hdrs = ["461.HammingDistance.h"],
	srcs = ["461.HammingDistance.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "461HammingDistanceTest",
	srcs  = ["461.HammingDistanceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["461HammingDistance",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "190ReverseBits",
	hdrs = ["190.ReverseBits.h"],
	srcs = ["190.ReverseBits.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "190ReverseBitsTest",
	srcs  = ["190.ReverseBitsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["190ReverseBits",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "136SingleNumber",
	hdrs = ["136.SingleNumber.h"],
	srcs = ["136.SingleNumber.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "136SingleNumberTest",
	srcs  = ["136.SingleNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["136SingleNumber",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "342PowerofFour",
	hdrs = ["342.PowerofFour.h"],
	srcs = ["342.PowerofFour.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "342PowerofFourTest",
	srcs  = ["342.PowerofFourTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["342PowerofFour",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "318MaximumProductofWordLengths",
	hdrs = ["318.MaximumProductofWordLengths.h"],
	srcs = ["318.MaximumProductofWordLengths.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "318MaximumProductofWordLengthsTest",
	srcs  = ["318.MaximumProductofWordLengthsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["318MaximumProductofWordLengths",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "338CountingBits",
	hdrs = ["338.CountingBits.h"],
	srcs = ["338.CountingBits.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "338CountingBitsTest",
	srcs  = ["338.CountingBitsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["338CountingBits",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "268MissingNumber",
	hdrs = ["268.MissingNumber.h"],
	srcs = ["268.MissingNumber.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "268MissingNumberTest",
	srcs  = ["268.MissingNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["268MissingNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "693BinaryNumberwithAlternatingBits",
	hdrs = ["693.BinaryNumberwithAlternatingBits.h"],
	srcs = ["693.BinaryNumberwithAlternatingBits.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "693BinaryNumberwithAlternatingBitsTest",
	srcs  = ["693.BinaryNumberwithAlternatingBitsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["693BinaryNumberwithAlternatingBits",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "260SingleNumberIII",
	hdrs = ["260.SingleNumberIII.h"],
	srcs = ["260.SingleNumberIII.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "260SingleNumberIIITest",
	srcs  = ["260.SingleNumberIIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["260SingleNumberIII",
			 "@googletest//:gtest_main"],
)