cc_library(
	name = "215KthLargestElementinanArray",
	hdrs = ["215.KthLargestElementinanArray.h"],
	srcs = ["215.KthLargestElementinanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "215KthLargestElementinanArrayTest",
	srcs  = ["215.KthLargestElementinanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["215KthLargestElementinanArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "347TopKFrequentElements",
	hdrs = ["347.TopKFrequentElements.h"],
	srcs = ["347.TopKFrequentElements.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "347TopKFrequentElementsTest",
	srcs  = ["347.TopKFrequentElementsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["347TopKFrequentElements",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "451SortCharactersByFrequency",
	hdrs = ["451.SortCharactersByFrequency.h"],
	srcs = ["451.SortCharactersByFrequency.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "451SortCharactersByFrequencyTest",
	srcs  = ["451.SortCharactersByFrequencyTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["451SortCharactersByFrequency",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "75SortColors",
	hdrs = ["75.SortColors.h"],
	srcs = ["75.SortColors.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "75SortColorsTest",
	srcs  = ["75.SortColorsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["75SortColors",
			 "@googletest//:gtest_main"],
)