cc_library(
	name = "215KthLargestElementinanArray",
	hdrs = ["215.KthLargestElementinanArray.h"],
	srcs = ["215.KthLargestElementinanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "215KthLargestElementinanArrayTest",
	srcs  = ["215.KthLargestElementinanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["215KthLargestElementinanArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "347TopKFrequentElements",
	hdrs = ["347.TopKFrequentElements.h"],
	srcs = ["347.TopKFrequentElements.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "347TopKFrequentElementsTest",
	srcs  = ["347.TopKFrequentElementsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["347TopKFrequentElements",
			 "@googletest//:gtest_main"],
)
