cc_library(
	name = "215KthLargestElementinanArray",
	hdrs = ["215.KthLargestElementinanArray.h"],
	srcs = ["215.KthLargestElementinanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "215KthLargestElementinanArrayTest",
	srcs  = ["215.KthLargestElementinanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["215KthLargestElementinanArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "347TopKFrequentElements",
	hdrs = ["347.TopKFrequentElements.h"],
	srcs = ["347.TopKFrequentElements.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "347TopKFrequentElementsTest",
	srcs  = ["347.TopKFrequentElementsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["347TopKFrequentElements",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "451SortCharactersByFrequency",
	hdrs = ["451.SortCharactersByFrequency.h"],
	srcs = ["451.SortCharactersByFrequency.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "451SortCharactersByFrequencyTest",
	srcs  = ["451.SortCharactersByFrequencyTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["451SortCharactersByFrequency",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "75SortColors",
	hdrs = ["75.SortColors.h"],
	srcs = ["75.SortColors.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "75SortColorsTest",
	srcs  = ["75.SortColorsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["75SortColors",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "179LargestNumber",
	hdrs = ["179.LargestNumber.h"],
	srcs = ["179.LargestNumber.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "179LargestNumberTest",
	srcs  = ["179.LargestNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["179LargestNumber",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "502IPO",
	hdrs = ["502.IPO.h"],
	srcs = ["502.IPO.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "502IPOTest",
	srcs  = ["502.IPOTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["502IPO",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "373FindKPairswithSmallestSums",
	hdrs = ["373.FindKPairswithSmallestSums.h"],
	srcs = ["373.FindKPairswithSmallestSums.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "373FindKPairswithSmallestSumsTest",
	srcs  = ["373.FindKPairswithSmallestSumsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["373FindKPairswithSmallestSums",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "295FindMedianfromDataStream",
	hdrs = ["295.FindMedianfromDataStream.h"],
	srcs = ["295.FindMedianfromDataStream.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "295FindMedianfromDataStreamTest",
	srcs  = ["295.FindMedianfromDataStreamTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["295FindMedianfromDataStream",
			 "@googletest//:gtest_main"],
)