cc_library(
	name = "695MaxAreaofIsland",
	hdrs = ["695.MaxAreaofIsland.h"],
	srcs = ["695.MaxAreaofIsland.cpp"]
)

cc_binary(
	name  = "695MaxAreaofIslandTest",
	srcs  = ["695.MaxAreaofIslandTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["695MaxAreaofIsland",
			 "@googletest//:gtest_main"],
)
