workspace(name = "leetcodeProject")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") 

new_git_repository(
    name = "googletest",
    build_file = "gmock.BUILD",
    remote = "https://github.com/google/googletest",
    tag = "release-1.10.0",
)