cc_library(
	name = "1_twoSum",
	hdrs = ["header.h"],
	srcs = ["1.twoSum.cc"]
)

cc_binary(
	name  = "twoSumTest",
	srcs  = ["1.twoSumTest.cc"],
	copts = ["-std=c++11"],
	deps  = ["1_twoSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "Median",
	hdrs = ["arraycomm.h",
			"4.MedianOfTwoSortedArrays.h",
		],
	srcs = ["4.MedianOfTwoSortedArrays.cpp"]
)

cc_binary(
	name  = "MedianTest",
	srcs  = ["4.MedianOfTwoSortedArraysTest.cpp",
		],
	copts = ["-std=c++11"],
	deps  = ["Median",
			 "@googletest//:gtest_main"],
)

cc_binary(
	name  = "otherTest",
	srcs  = ["otherTest.cc",
		],
	copts = ["-std=c++11"],
	deps  = ["Median"],
)


cc_library(
	name = "7ReverseInteger",
	hdrs = ["7.ReverseInteger.h"],
	srcs = ["7.ReverseInteger.cpp"]
)

cc_binary(
	name  = "7ReverseIntegerTest",
	srcs  = ["7.ReverseIntegerTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["7ReverseInteger",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "9PalindromeNumber",
	hdrs = ["9.PalindromeNumber.h"],
	srcs = ["9.PalindromeNumber.cpp"]
)

cc_binary(
	name  = "9PalindromeNumberTest",
	srcs  = ["9.PalindromeNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["9PalindromeNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1200MinimumAbsoluteDifference",
	hdrs = ["1200.MinimumAbsoluteDifference.h"],
	srcs = ["1200.MinimumAbsoluteDifference.cpp"]
)

cc_binary(
	name  = "1200MinimumAbsoluteDifferenceTest",
	srcs  = ["1200.MinimumAbsoluteDifferenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1200MinimumAbsoluteDifference",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "11ContainerWithMostWater",
	hdrs = ["11.ContainerWithMostWater.h"],
	srcs = ["11.ContainerWithMostWater.cpp"]
)

cc_binary(
	name  = "11ContainerWithMostWaterTest",
	srcs  = ["11.ContainerWithMostWaterTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["11ContainerWithMostWater",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "121BestTimetoBuyandSellStock",
	hdrs = ["121.BestTimetoBuyandSellStock.h"],
	srcs = ["121.BestTimetoBuyandSellStock.cpp"]
)

cc_binary(
	name  = "121BestTimetoBuyandSellStockTest",
	srcs  = ["121.BestTimetoBuyandSellStockTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["121BestTimetoBuyandSellStock",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "646MaximumLengthofPairChain",
	hdrs = ["646.MaximumLengthofPairChain.h"],
	srcs = ["646.MaximumLengthofPairChain.cpp"]
)

cc_binary(
	name  = "646MaximumLengthofPairChainTest",
	srcs  = ["646.MaximumLengthofPairChainTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["646MaximumLengthofPairChain",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "448FindAllNumbersDisappearedinanArray",
	hdrs = ["448.FindAllNumbersDisappearedinanArray.h"],
	srcs = ["448.FindAllNumbersDisappearedinanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "448FindAllNumbersDisappearedinanArrayTest",
	srcs  = ["448.FindAllNumbersDisappearedinanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["448FindAllNumbersDisappearedinanArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "240Searcha2DMatrixII",
	hdrs = ["240.Searcha2DMatrixII.h"],
	srcs = ["240.Searcha2DMatrixII.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "240Searcha2DMatrixIITest",
	srcs  = ["240.Searcha2DMatrixIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["240Searcha2DMatrixII",
			 "@googletest//:gtest_main"],
)