cc_library(
	name = "1_twoSum",
	hdrs = ["header.h"],
	srcs = ["1.twoSum.cc"]
)

cc_binary(
	name  = "twoSumTest",
	srcs  = ["1.twoSumTest.cc"],
	copts = ["-std=c++11"],
	deps  = ["1_twoSum",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "26RemoveDuplicatesfromSortedArray",
	hdrs = ["26.RemoveDuplicatesfromSortedArray.h"],
	srcs = ["26.RemoveDuplicatesfromSortedArray.cpp"]
)

cc_binary(
	name  = "26RemoveDuplicatesfromSortedArrayTest",
	srcs  = ["26.RemoveDuplicatesfromSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["26RemoveDuplicatesfromSortedArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "27RemoveElement",
	hdrs = ["27.RemoveElement.h"],
	srcs = ["27.RemoveElement.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "27RemoveElementTest",
	srcs  = ["27.RemoveElementTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["27RemoveElement",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "Median",
	hdrs = ["arraycomm.h",
			"4.MedianOfTwoSortedArrays.h",
		],
	srcs = ["4.MedianOfTwoSortedArrays.cpp"]
)

cc_binary(
	name  = "MedianTest",
	srcs  = ["4.MedianOfTwoSortedArraysTest.cpp",
		],
	copts = ["-std=c++11"],
	deps  = ["Median",
			 "@googletest//:gtest_main"],
)

cc_binary(
	name  = "otherTest",
	srcs  = ["otherTest.cc",
		],
	copts = ["-std=c++11"],
	deps  = ["Median"],
)


cc_library(
	name = "7ReverseInteger",
	hdrs = ["7.ReverseInteger.h"],
	srcs = ["7.ReverseInteger.cpp"]
)

cc_binary(
	name  = "7ReverseIntegerTest",
	srcs  = ["7.ReverseIntegerTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["7ReverseInteger",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "9PalindromeNumber",
	hdrs = ["9.PalindromeNumber.h"],
	srcs = ["9.PalindromeNumber.cpp"]
)

cc_binary(
	name  = "9PalindromeNumberTest",
	srcs  = ["9.PalindromeNumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["9PalindromeNumber",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1200MinimumAbsoluteDifference",
	hdrs = ["1200.MinimumAbsoluteDifference.h"],
	srcs = ["1200.MinimumAbsoluteDifference.cpp"]
)

cc_binary(
	name  = "1200MinimumAbsoluteDifferenceTest",
	srcs  = ["1200.MinimumAbsoluteDifferenceTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1200MinimumAbsoluteDifference",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "11ContainerWithMostWater",
	hdrs = ["11.ContainerWithMostWater.h"],
	srcs = ["11.ContainerWithMostWater.cpp"]
)

cc_binary(
	name  = "11ContainerWithMostWaterTest",
	srcs  = ["11.ContainerWithMostWaterTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["11ContainerWithMostWater",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "121BestTimetoBuyandSellStock",
	hdrs = ["121.BestTimetoBuyandSellStock.h"],
	srcs = ["121.BestTimetoBuyandSellStock.cpp"]
)

cc_binary(
	name  = "121BestTimetoBuyandSellStockTest",
	srcs  = ["121.BestTimetoBuyandSellStockTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["121BestTimetoBuyandSellStock",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "646MaximumLengthofPairChain",
	hdrs = ["646.MaximumLengthofPairChain.h"],
	srcs = ["646.MaximumLengthofPairChain.cpp"]
)

cc_binary(
	name  = "646MaximumLengthofPairChainTest",
	srcs  = ["646.MaximumLengthofPairChainTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["646MaximumLengthofPairChain",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "448FindAllNumbersDisappearedinanArray",
	hdrs = ["448.FindAllNumbersDisappearedinanArray.h"],
	srcs = ["448.FindAllNumbersDisappearedinanArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "448FindAllNumbersDisappearedinanArrayTest",
	srcs  = ["448.FindAllNumbersDisappearedinanArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["448FindAllNumbersDisappearedinanArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "48RotateImage",
	hdrs = ["48.RotateImage.h"],
	srcs = ["48.RotateImage.cpp"],
	copts = ["-std=c++11"],
)

cc_library(
	name = "240Searcha2DMatrixII",
	hdrs = ["240.Searcha2DMatrixII.h"],
	srcs = ["240.Searcha2DMatrixII.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "48RotateImageTest",
	srcs  = ["48.RotateImageTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["48RotateImage",
			"@googletest//:gtest_main"],
)

cc_binary(
	name  = "240Searcha2DMatrixIITest",
	srcs  = ["240.Searcha2DMatrixIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["240Searcha2DMatrixII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "769MaxChunksToMakeSorted",
	hdrs = ["769.MaxChunksToMakeSorted.h"],
	srcs = ["769.MaxChunksToMakeSorted.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "769MaxChunksToMakeSortedTest",
	srcs  = ["769.MaxChunksToMakeSortedTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["769MaxChunksToMakeSorted",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "566ReshapetheMatrix",
	hdrs = ["566.ReshapetheMatrix.h"],
	srcs = ["566.ReshapetheMatrix.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "566ReshapetheMatrixTest",
	srcs  = ["566.ReshapetheMatrixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["566ReshapetheMatrix",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "33SearchinRotatedSortedArray",
	hdrs = ["33.SearchinRotatedSortedArray.h"],
	srcs = ["33.SearchinRotatedSortedArray.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "33SearchinRotatedSortedArrayTest",
	srcs  = ["33.SearchinRotatedSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["33SearchinRotatedSortedArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "41FirstMissingPositive",
	hdrs = ["41.FirstMissingPositive.h"],
	srcs = ["41.FirstMissingPositive.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "41FirstMissingPositiveTest",
	srcs  = ["41.FirstMissingPositiveTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["41FirstMissingPositive",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "54SpiralMatrix",
	hdrs = ["54.SpiralMatrix.h"],
	srcs = ["54.SpiralMatrix.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "54SpiralMatrixTest",
	srcs  = ["54.SpiralMatrixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["54SpiralMatrix",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "59SpiralMatrixII",
	hdrs = ["59.SpiralMatrixII.h"],
	srcs = ["59.SpiralMatrixII.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "59SpiralMatrixIITest",
	srcs  = ["59.SpiralMatrixIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["59SpiralMatrixII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "66PlusOne",
	hdrs = ["66.PlusOne.h"],
	srcs = ["66.PlusOne.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "66PlusOneTest",
	srcs  = ["66.PlusOneTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["66PlusOne",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "67AddBinary",
	hdrs = ["67.AddBinary.h"],
	srcs = ["67.AddBinary.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "67AddBinaryTest",
	srcs  = ["67.AddBinaryTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["67AddBinary",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "73SetMatrixZeroes",
	hdrs = ["73.SetMatrixZeroes.h"],
	srcs = ["73.SetMatrixZeroes.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "73SetMatrixZeroesTest",
	srcs  = ["73.SetMatrixZeroesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["73SetMatrixZeroes",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "74Searcha2DMatrix",
	hdrs = ["74.Searcha2DMatrix.h"],
	srcs = ["74.Searcha2DMatrix.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "74Searcha2DMatrixTest",
	srcs  = ["74.Searcha2DMatrixTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["74Searcha2DMatrix",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "78Subsets",
	hdrs = ["78.Subsets.h"],
	srcs = ["78.Subsets.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "78SubsetsTest",
	srcs  = ["78.SubsetsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["78Subsets",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "80RemoveDuplicatesfromSortedArrayII",
	hdrs = ["80.RemoveDuplicatesfromSortedArrayII.h"],
	srcs = ["80.RemoveDuplicatesfromSortedArrayII.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "80RemoveDuplicatesfromSortedArrayIITest",
	srcs  = ["80.RemoveDuplicatesfromSortedArrayIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["80RemoveDuplicatesfromSortedArrayII",
			 "@googletest//:gtest_main"],
)