cc_library(
	name = "210CourseScheduleII",
	hdrs = ["210.CourseScheduleII.h"],
	srcs = ["210.CourseScheduleII.cpp"]
)

cc_binary(
	name  = "210CourseScheduleIITest",
	srcs  = ["210.CourseScheduleIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["210CourseScheduleII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "785IsGraphBipartite",
	hdrs = ["785.IsGraphBipartite.h"],
	srcs = ["785.IsGraphBipartite.cpp"]
)

cc_binary(
	name  = "785IsGraphBipartiteTest",
	srcs  = ["785.IsGraphBipartiteTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["785IsGraphBipartite",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "684RedundantConnection",
	hdrs = ["684.RedundantConnection.h"],
	srcs = ["684.RedundantConnection.cpp"]
)

cc_binary(
	name  = "684RedundantConnectionTest",
	srcs  = ["684.RedundantConnectionTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["684RedundantConnection",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "207CourseSchedule",
	hdrs = ["207.CourseSchedule.h"],
	srcs = ["207.CourseSchedule.cpp"]
)

cc_binary(
	name  = "207CourseScheduleTest",
	srcs  = ["207.CourseScheduleTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["207CourseSchedule",
			 "@googletest//:gtest_main"],
)