cc_library(
	name = "210CourseScheduleII",
	hdrs = ["210.CourseScheduleII.h"],
	srcs = ["210.CourseScheduleII.cpp"]
)

cc_binary(
	name  = "210CourseScheduleIITest",
	srcs  = ["210.CourseScheduleIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["210CourseScheduleII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "785IsGraphBipartite",
	hdrs = ["785.IsGraphBipartite.h"],
	srcs = ["785.IsGraphBipartite.cpp"]
)

cc_binary(
	name  = "785IsGraphBipartiteTest",
	srcs  = ["785.IsGraphBipartiteTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["785IsGraphBipartite",
			 "@googletest//:gtest_main"],
)