cc_library(
	name = "46Permutations",
	hdrs = ["46.Permutations.h"],
	srcs = ["46.Permutations.cpp"]
)

cc_binary(
	name  = "46PermutationsTest",
	srcs  = ["46.PermutationsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["46Permutations",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "77Combinations",
	hdrs = ["77.Combinations.h"],
	srcs = ["77.Combinations.cpp"]
)

cc_binary(
	name  = "77CombinationsTest",
	srcs  = ["77.CombinationsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["77Combinations",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "79WordSearch",
	hdrs = ["79.WordSearch.h"],
	srcs = ["79.WordSearch.cpp"]
)

cc_binary(
	name  = "79WordSearchTest",
	srcs  = ["79.WordSearchTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["79WordSearch",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "51NQueens",
	hdrs = ["51.N-Queens.h"],
	srcs = ["51.N-Queens.cpp"]
)

cc_binary(
	name  = "51NQueensTest",
	srcs  = ["51.N-QueensTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["51NQueens",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "126.WordLadderII",
	hdrs = ["126.WordLadderII.h"],
	srcs = ["126.WordLadderII.cpp"]
)

cc_binary(
	name  = "126WordLadderIITest",
	srcs  = ["126.WordLadderIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["126.WordLadderII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "47PermutationsII",
	hdrs = ["47.PermutationsII.h"],
	srcs = ["47.PermutationsII.cpp"]
)

cc_binary(
	name  = "47PermutationsIITest",
	srcs  = ["47.PermutationsIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["47PermutationsII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "40CombinationSumII",
	hdrs = ["40.CombinationSumII.h"],
	srcs = ["40.CombinationSumII.cpp"]
)

cc_binary(
	name  = "40CombinationSumIITest",
	srcs  = ["40.CombinationSumIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["40CombinationSumII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "52N-QueensII",
	hdrs = ["52.N-QueensII.h"],
	srcs = ["52.N-QueensII.cpp"]
)

cc_binary(
	name  = "52N-QueensIITest",
	srcs  = ["52.N-QueensIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["52N-QueensII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "127WordLadder",
	hdrs = ["127.WordLadder.h"],
	srcs = ["127.WordLadder.cpp"]
)

cc_binary(
	name  = "127WordLadderTest",
	srcs  = ["127.WordLadderTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["127WordLadder",
			 "@googletest//:gtest_main"],
)
