cc_library(
	name = "46Permutations",
	hdrs = ["46.Permutations.h"],
	srcs = ["46.Permutations.cpp"]
)

cc_binary(
	name  = "46PermutationsTest",
	srcs  = ["46.PermutationsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["46Permutations",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "77Combinations",
	hdrs = ["77.Combinations.h"],
	srcs = ["77.Combinations.cpp"]
)

cc_binary(
	name  = "77CombinationsTest",
	srcs  = ["77.CombinationsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["77Combinations",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "79WordSearch",
	hdrs = ["79.WordSearch.h"],
	srcs = ["79.WordSearch.cpp"]
)

cc_binary(
	name  = "79WordSearchTest",
	srcs  = ["79.WordSearchTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["79WordSearch",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "51NQueens",
	hdrs = ["51.N-Queens.h"],
	srcs = ["51.N-Queens.cpp"]
)

cc_binary(
	name  = "51NQueensTest",
	srcs  = ["51.N-QueensTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["51NQueens",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "126.WordLadderII",
	hdrs = ["126.WordLadderII.h"],
	srcs = ["126.WordLadderII.cpp"]
)

cc_binary(
	name  = "126WordLadderIITest",
	srcs  = ["126.WordLadderIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["126.WordLadderII",
			 "@googletest//:gtest_main"],
)