cc_library(
	name = "455AssignCookies",
	hdrs = ["455.AssignCookies.h"],
	srcs = ["455.AssignCookies.cpp"]
)

cc_binary(
	name  = "455AssignCookiesTest",
	srcs  = ["455.AssignCookiesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["455AssignCookies",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "135Candy",
	hdrs = ["135.Candy.h"],
	srcs = ["135.Candy.cpp"]
)

cc_binary(
	name  = "135CandyTest",
	srcs  = ["135.CandyTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["135Candy",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "435NonOverlappingIntervals",
	hdrs = ["435.NonOverlappingIntervals.h"],
	srcs = ["435.NonOverlappingIntervals.cpp"]
)

cc_binary(
	name  = "435NonOverlappingIntervalsTest",
	srcs  = ["435.NonOverlappingIntervalsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["435NonOverlappingIntervals",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "605CanPlaceFlower",
	hdrs = ["605.CanPlaceFlowers.h"],
	srcs = ["605.CanPlaceFlowers.cpp"]
)

cc_binary(
	name  = "605CanPlaceFlowerTest",
	srcs  = ["605.CanPlaceFlowersTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["605CanPlaceFlower",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "452MinimumNumberofArrowstoBurstBalloons",
	hdrs = ["452.MinimumNumberofArrowstoBurstBalloons.h"],
	srcs = ["452.MinimumNumberofArrowstoBurstBalloons.cpp"]
)

cc_binary(
	name  = "452MinimumNumberofArrowstoBurstBalloonsTest",
	srcs  = ["452.MinimumNumberofArrowstoBurstBalloonsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["452MinimumNumberofArrowstoBurstBalloons",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "763PartitionLabels",
	hdrs = ["763.PartitionLabels.h"],
	srcs = ["763.PartitionLabels.cpp"]
)

cc_binary(
	name  = "763PartitionLabelsTest",
	srcs  = ["763.PartitionLabelsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["763PartitionLabels",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "122BestTimetoBuyandSellStockII",
	hdrs = ["122.BestTimetoBuyandSellStockII.h"],
	srcs = ["122.BestTimetoBuyandSellStockII.cpp"]
)

cc_binary(
	name  = "122BestTimetoBuyandSellStockIITest",
	srcs  = ["122.BestTimetoBuyandSellStockIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["122BestTimetoBuyandSellStockII",
			 "@googletest//:gtest_main"],
)
