cc_library(
	name = "455AssignCookies",
	hdrs = ["455.AssignCookies.h"],
	srcs = ["455.AssignCookies.cpp"]
)

cc_binary(
	name  = "455AssignCookiesTest",
	srcs  = ["455.AssignCookiesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["455AssignCookies",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "135Candy",
	hdrs = ["135.Candy.h"],
	srcs = ["135.Candy.cpp"]
)

cc_binary(
	name  = "135CandyTest",
	srcs  = ["135.CandyTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["135Candy",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "435NonOverlappingIntervals",
	hdrs = ["435.NonOverlappingIntervals.h"],
	srcs = ["435.NonOverlappingIntervals.cpp"]
)

cc_binary(
	name  = "435NonOverlappingIntervalsTest",
	srcs  = ["435.NonOverlappingIntervalsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["435NonOverlappingIntervals",
			 "@googletest//:gtest_main"],
)