cc_library(
	name = "455AssignCookies",
	hdrs = ["455.AssignCookies.h"],
	srcs = ["455.AssignCookies.cpp"]
)

cc_binary(
	name  = "455AssignCookiesTest",
	srcs  = ["455.AssignCookiesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["455AssignCookies",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "135Candy",
	hdrs = ["135.Candy.h"],
	srcs = ["135.Candy.cpp"]
)

cc_binary(
	name  = "135CandyTest",
	srcs  = ["135.CandyTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["135Candy",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "435NonOverlappingIntervals",
	hdrs = ["435.NonOverlappingIntervals.h"],
	srcs = ["435.NonOverlappingIntervals.cpp"]
)

cc_binary(
	name  = "435NonOverlappingIntervalsTest",
	srcs  = ["435.NonOverlappingIntervalsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["435NonOverlappingIntervals",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "605CanPlaceFlower",
	hdrs = ["605.CanPlaceFlowers.h"],
	srcs = ["605.CanPlaceFlowers.cpp"]
)

cc_binary(
	name  = "605CanPlaceFlowerTest",
	srcs  = ["605.CanPlaceFlowersTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["605CanPlaceFlower",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "452MinimumNumberofArrowstoBurstBalloons",
	hdrs = ["452.MinimumNumberofArrowstoBurstBalloons.h"],
	srcs = ["452.MinimumNumberofArrowstoBurstBalloons.cpp"]
)

cc_binary(
	name  = "452MinimumNumberofArrowstoBurstBalloonsTest",
	srcs  = ["452.MinimumNumberofArrowstoBurstBalloonsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["452MinimumNumberofArrowstoBurstBalloons",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "763PartitionLabels",
	hdrs = ["763.PartitionLabels.h"],
	srcs = ["763.PartitionLabels.cpp"]
)

cc_binary(
	name  = "763PartitionLabelsTest",
	srcs  = ["763.PartitionLabelsTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["763PartitionLabels",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "122BestTimetoBuyandSellStockII",
	hdrs = ["122.BestTimetoBuyandSellStockII.h"],
	srcs = ["122.BestTimetoBuyandSellStockII.cpp"]
)

cc_binary(
	name  = "122BestTimetoBuyandSellStockIITest",
	srcs  = ["122.BestTimetoBuyandSellStockIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["122BestTimetoBuyandSellStockII",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "406QueueReconstructionbyHeight",
	hdrs = ["406.QueueReconstructionbyHeight.h"],
	srcs = ["406.QueueReconstructionbyHeight.cpp"]
)

cc_binary(
	name  = "406QueueReconstructionbyHeightTest",
	srcs  = ["406.QueueReconstructionbyHeightTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["406QueueReconstructionbyHeight",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "665NondecreasingArray",
	hdrs = ["665.NondecreasingArray.h"],
	srcs = ["665.NondecreasingArray.cpp"]
)

cc_binary(
	name  = "665NondecreasingArrayTest",
	srcs  = ["665.NondecreasingArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["665NondecreasingArray",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "1323Maximum69Number",
	hdrs = ["1323.Maximum69Number.h"],
	srcs = ["1323.Maximum69Number.cpp"]
)

cc_binary(
	name  = "1323Maximum69NumberTest",
	srcs  = ["1323.Maximum69NumberTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["1323Maximum69Number",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "870AdvantageShuffle",
	hdrs = ["870.AdvantageShuffle.h"],
	srcs = ["870.AdvantageShuffle.cpp"]
)

cc_binary(
	name  = "870AdvantageShuffleTest",
	srcs  = ["870.AdvantageShuffleTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["870AdvantageShuffle",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "55JumpGame",
	hdrs = ["55.JumpGame.h"],
	srcs = ["55.JumpGame.cpp"]
)

cc_binary(
	name  = "55JumpGameTest",
	srcs  = ["55.JumpGameTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["55JumpGame",
			 "@googletest//:gtest_main"],
)