cc_library(
	name = "232ImplementQueueusingStacks",
	hdrs = ["232.ImplementQueueusingStacks.h"],
	srcs = ["232.ImplementQueueusingStacks.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "232ImplementQueueusingStacksTest",
	srcs  = ["232.ImplementQueueusingStacksTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["232ImplementQueueusingStacks",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "155MinStack",
	hdrs = ["155.MinStack.h"],
	srcs = ["155.MinStack.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "155MinStackTest",
	srcs  = ["155.MinStackTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["155MinStack",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "20ValidParentheses",
	hdrs = ["20.ValidParentheses.h"],
	srcs = ["20.ValidParentheses.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "20ValidParenthesesTest",
	srcs  = ["20.ValidParenthesesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["20ValidParentheses",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "739DailyTemperatures",
	hdrs = ["739.DailyTemperatures.h"],
	srcs = ["739.DailyTemperatures.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "739DailyTemperaturesTest",
	srcs  = ["739.DailyTemperaturesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["739DailyTemperatures",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "218TheSkylineProblem",
	hdrs = ["218.TheSkylineProblem.h"],
	srcs = ["218.TheSkylineProblem.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "218TheSkylineProblemTest",
	srcs  = ["218.TheSkylineProblemTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["218TheSkylineProblem",
			 "@googletest//:gtest_main"],
)



cc_library(
	name = "239SlidingWindowMaximum",
	hdrs = ["239.SlidingWindowMaximum.h"],
	srcs = ["239.SlidingWindowMaximum.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "239SlidingWindowMaximumTest",
	srcs  = ["239.SlidingWindowMaximumTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["239SlidingWindowMaximum",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "225ImplementStackusingQueues",
	hdrs = ["225.ImplementStackusingQueues.h"],
	srcs = ["225.ImplementStackusingQueues.cpp"],
    copts = ["-std=c++11"],
)

cc_binary(
	name  = "225ImplementStackusingQueuesTest",
	srcs  = ["225.ImplementStackusingQueuesTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["225ImplementStackusingQueues",
			 "@googletest//:gtest_main"],
)