cc_library(
	name = "167TwoSumIIInputArrayIsSorted",
	hdrs = ["167.TwoSumII-InputArrayIsSorted.h"],
	srcs = ["167.TwoSumII-InputArrayIsSorted.cpp"]
)

cc_binary(
	name  = "167TwoSumIIInputArrayIsSortedTest",
	srcs  = ["167.TwoSumII-InputArrayIsSortedTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["167TwoSumIIInputArrayIsSorted",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "88MergeSortedArray",
	hdrs = ["88.MergeSortedArray.h"],
	srcs = ["88.MergeSortedArray.cpp"]
)

cc_binary(
	name  = "88MergeSortedArrayTest",
	srcs  = ["88.MergeSortedArrayTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["88MergeSortedArray",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "633SumofSquareNumbers",
	hdrs = ["633.SumofSquareNumbers.h"],
	srcs = ["633.SumofSquareNumbers.cpp"]
)

cc_binary(
	name  = "633SumofSquareNumbersTest",
	srcs  = ["633.SumofSquareNumbersTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["633SumofSquareNumbers",
			 "@googletest//:gtest_main"],
)

cc_library(
	name = "76MinimumWindowSubstring",
	hdrs = ["76.MinimumWindowSubstring.h"],
	srcs = ["76.MinimumWindowSubstring.cpp"]
)

cc_binary(
	name  = "76MinimumWindowSubstringTest",
	srcs  = ["76.MinimumWindowSubstringTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["76MinimumWindowSubstring",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "680ValidPalindromeII",
	hdrs = ["680.ValidPalindromeII.h"],
	srcs = ["680.ValidPalindromeII.cpp"]
)

cc_binary(
	name  = "680ValidPalindromeIITest",
	srcs  = ["680.ValidPalindromeIITest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["680ValidPalindromeII",
			 "@googletest//:gtest_main"],
)


cc_library(
	name = "42TrappingRainWater",
	hdrs = ["42.TrappingRainWater.h"],
	srcs = ["42.TrappingRainWater.cpp"]
)

cc_binary(
	name  = "42TrappingRainWaterTest",
	srcs  = ["42.TrappingRainWaterTest.cpp"],
	copts = ["-std=c++11"],
	deps  = ["42TrappingRainWater",
			 "@googletest//:gtest_main"],
)