cc_library(
    name = "oshook",
    hdrs = ["os_hook.h"],
    srcs = ["os_hook.cpp"],
    copts = ["-std=c++11"],
    deps = ["//lib/comm/class:nocopyable"],
    visibility = ["//visibility:public"],
)